# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeui < Formula
  desc "Kubernetes monitoring and management UI"
  homepage "https://github.com/opengittr/kubeui"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OpenGittr/kubeui/releases/download/v0.3.0/kubeui_darwin_amd64.tar.gz"
      sha256 "cd04d6c13fb6146aaa732a7dbf432388e689faa516bcc166856c2fee1c1887d1"

      define_method(:install) do
        bin.install "kubeui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OpenGittr/kubeui/releases/download/v0.3.0/kubeui_darwin_arm64.tar.gz"
      sha256 "9e7c4308204c3717bfb2e75201d7d5fde3cb32f317e6a833437a8a0c06f67f93"

      define_method(:install) do
        bin.install "kubeui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpenGittr/kubeui/releases/download/v0.3.0/kubeui_linux_amd64.tar.gz"
      sha256 "df9a6d3828bb4f00be2db79e58df645e6c9f5471b0ddd6301ba87fe0f15d3ef4"
      define_method(:install) do
        bin.install "kubeui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpenGittr/kubeui/releases/download/v0.3.0/kubeui_linux_arm64.tar.gz"
      sha256 "e72cb68acf2fddce3c9f04a0621d16648ce248f96732381b55dca8783da80149"
      define_method(:install) do
        bin.install "kubeui"
      end
    end
  end
end
