# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeui < Formula
  desc "Kubernetes monitoring and management UI"
  homepage "https://github.com/opengittr/kubeui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OpenGittr/kubeui/releases/download/v0.1.0/kubeui_darwin_amd64.tar.gz"
      sha256 "321ae55d97b48e6562bcbf7902d7417551f3a3f26e408b073b70133c6de49ab3"

      def install
        bin.install "kubeui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OpenGittr/kubeui/releases/download/v0.1.0/kubeui_darwin_arm64.tar.gz"
      sha256 "3180744e58ad5484eccecac3568f91bdfd7d9cb2035d56efa9536a87dc97398e"

      def install
        bin.install "kubeui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpenGittr/kubeui/releases/download/v0.1.0/kubeui_linux_amd64.tar.gz"
      sha256 "25982cd4af5736c056794bb41829a01c9ca81045dd72d7fcdc5ec4d326161ea6"
      def install
        bin.install "kubeui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpenGittr/kubeui/releases/download/v0.1.0/kubeui_linux_arm64.tar.gz"
      sha256 "31af28f81b1bce33d1a1fb91e8cdbec17f5c28c46b5f761c3666c6f6d1aaca56"
      def install
        bin.install "kubeui"
      end
    end
  end
end
